# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "feature/trail" ]
  pull_request:
    branches: [ "feature/trail" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # You can change to your preferred version

      - name: Install ChromeDriver using Chocolatey
        run: |
          choco install chromedriver --ignore-checksums -y
          choco install googlechrome --ignore-checksums -y

      - name: Add ChromeDriver to PATH
        run: echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run : |
          python 10th_marks_automate.py


